version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/usr/src/app
#    command: sh -c "sleep infinity"
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
